Prueba3/models/News.php
<?php

namespace app\models;

use Yii;
use \yii\db\ActiveRecord;
use yii\base\Model;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\SluggableBehavior;

class News extends \yii\db\ActiveRecord {

    public $file;

    /**
     * @property integer $id
     * @property string $title
     * @property string $body
     * @property integer $sections_id
     * @property integer $created_at
     * @property integer $updated_at
     * @property string  $image
     * @property string  $slug
     * @property Sections $sections
     */
    public static function tableName() {

        return 'news';
    }

    public function rules() {


        return
                    [
                        [['title', 'body', 'sections_id', 'image'], 'required'],
        ];
    }

    public function behaviors() {
        return [
                [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
            ], [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
            ],
        ];
    }

    public function upload() {
        if ($this->validate()) {
            $this->file->saveAs('img/' . $this->foto->baseName . '.' . $this->file->extension);

            return true;
        } else {
            return false;
        }
    }

    public function attributeLabels() {

        return
                    [
                    'id' => 'Identificador',
                    'title' => 'Titulo',
                    'body' => 'Cuerpo',
                    'sections_id' => 'Seccion',
                    'created_at' => 'Fecha_Creacion',
                    'updated_at' => 'Fecha_Actualizado',
                    'file' => 'image',
        ];
    }

    public function getSections() {



        return $this->hasMany(Sections::ClassName(), ['id' => 'sections_id']);
    }

}

Prueba3/controllers/NewsController.php
<?php

namespace app\controllers;

use app\models\Sections;
use app\models\News;
use app\models\Upload;
use yii\web\Controller;
use yii\widgets\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use Yii;
use app\models\form;
use yii\web\UploadedFile;

class NewsController extends Controller {

    public function actionForm() {

        $model = new News();
    
        if ($model->load(Yii::$app->request->post())) {
            $prueba = UploadedFile::getInstance($model, 'image');
            $prueba->saveAs('img/' . $prueba->name);
            $model->image = $prueba->name;
            if (!$model->save()) {

                return $this->render('form', ['model' => $model,
                            'sections' => $this->getSectionsOnArray()]);
            } else {

                $this->redirect(['news/detalle/'.$model->slug]);
            }
        } else {

            return $this->render('form', ['model' => $model,
                        'sections' => $this->getSectionsOnArray()]);
        }
    }
    
    
    public function actionDetalle($slug){
         
        $noticia= News::findOne(['slug'=>$slug]);
        $notice=$noticia->slug;
        print_r($notice);  
        return $this->render('detalle',['noticia'=>$noticia]);
       
        
    }

    private function findModelBySlug($slug) {
        if (($model = News::find()->where(['slug'=>$slug])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException();
        }
    }

    public function actionCreate() {
        $model = new News();
        $model->load(Yii::$app->request->post());
        $model->save();
        return $this->render('form', ['model' => $model]);
    }

    public function actionIndex() {
        $model= new News();
        $DataProvider = new ActiveDataProvider([
            'query' => News::find(),
            'pagination' => ['pagesize' => 10,],]);
        return $this->render('index', ['DataProvider' => $DataProvider,'model'=>$model]);
    }

    private function getSectionsOnArray() {

        return ArrayHelper::map(Sections::find()->all(), 'id', 'name');
    }

}

Prueba3/views/News/_post.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;

?>
<div class="post">
    
    <h2><?= Html::encode($model->id) ?></h2>
    <?= HtmlPurifier::process($model->title) ?>
    <br>    
    <?= HtmlPurifier::process($model->body) ?>    
    <?= Html::img('img/'.$model->image);?> 
   
</div>

Prueba3/views/News/detalle.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
echo 'DETALLE';
$img=Html::img('@web/img/image');
echo DetailView::widget([
    'model' => $noticia,
    'attributes'=>[
    'title',
   'image',
    'body'],
    
]);


echo Html::a('Regresa', ['/news/index'], ['class'=>'btn btn-primary']); ?>

Prueba3/views/News/form.php
<?php
use   yii\widgets\ActiveForm;
use yii\helpers\Html;


$form = ActiveForm::begin([
    'id' => 'login-form',
    'options' => ['class' => 'form-horizontal',
        'enctype' => 'multipart/form-data'],
]) 
?>
   <?= $form->errorSummary($model); ?>
    <?= $form->field($model, 'title') ?>
    <?= $form->field($model, 'body')->textArea(['rows' => '6']) ?>
    <?= $form->field($model, 'sections_id')->dropdownList($sections,
                                ['prompt'=>'Selecciona una categoría']); ?>
    <?= $form->field($model,'image')->fileInput() ?>
<div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Agrega', ['class' => 'btn btn-primary']) ?>
        </div>
</div>
<?php ActiveForm::end() ?>

Prueba3/views/News/index.php
<?php 
use yii\widgets\ListView;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Carousel;
?>

<div class="row">
<div class="col-lg-2">
              
<?php 
echo 'HOLA';
echo ListView::widget([
    'dataProvider' => $DataProvider,
    'itemView'=>'_post',
]); 
?>
</div>
    <center><div class="col-lg-10"><h1>Elementos de noticias</h1></div><br></center>
    
<br>

<?php
$url=Html::img('@web/img/Koala.jpg', ['alt' => 'My logo']);

echo '<br>'.Html::a( $url,Url::to(['news/form', 'slug' => $model->slug]) );


?>